/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from './home';
import * as import1 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import10 from 'ionic-angular/components/navbar/navbar';
import * as import11 from '../../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import12 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import13 from '../../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from '../../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from 'ionic-angular/components/button/button';
import * as import17 from '../../../node_modules/ionic-angular/components/button/button.ngfactory';
export declare class Wrapper_HomePage {
    _eventHandler: Function;
    context: import0.HomePage;
    _changed: boolean;
    constructor(p0: any);
    ngOnDetach(view: import1.AppView<any>, componentView: import1.AppView<any>, el: any): void;
    ngOnDestroy(): void;
    ngDoCheck(view: import1.AppView<any>, el: any, throwOnChange: boolean): boolean;
    checkHost(view: import1.AppView<any>, componentView: import1.AppView<any>, el: any, throwOnChange: boolean): void;
    handleEvent(eventName: string, $event: any): boolean;
    subscribe(view: import1.AppView<any>, _eventHandler: any): void;
}
export declare const HomePageNgFactory: import7.ComponentFactory<import0.HomePage>;
export declare class View_HomePage0 extends import1.AppView<import0.HomePage> {
    _text_0: any;
    _el_1: any;
    _Header_1_3: import9.Wrapper_Header;
    _text_2: any;
    _el_3: any;
    compView_3: import1.AppView<import10.Navbar>;
    _Navbar_3_3: import11.Wrapper_Navbar;
    _text_4: any;
    _el_5: any;
    compView_5: import1.AppView<import12.ToolbarTitle>;
    _ToolbarTitle_5_3: import13.Wrapper_ToolbarTitle;
    _text_6: any;
    _text_7: any;
    _text_8: any;
    _text_9: any;
    _el_10: any;
    compView_10: import1.AppView<import14.Content>;
    _Content_10_3: import15.Wrapper_Content;
    _text_11: any;
    _el_12: any;
    _text_13: any;
    _el_14: any;
    _text_15: any;
    _text_16: any;
    _text_17: any;
    _el_18: any;
    compView_18: import1.AppView<import16.Button>;
    _Button_18_3: import17.Wrapper_Button;
    _text_19: any;
    _text_20: any;
    _text_21: any;
    constructor(viewUtils: import3.ViewUtils, parentView: import1.AppView<any>, parentIndex: number, parentElement: any);
    createInternal(rootSelector: string): import7.ComponentRef<any>;
    injectorGetInternal(token: any, requestNodeIndex: number, notFoundResult: any): any;
    detectChangesInternal(throwOnChange: boolean): void;
    destroyInternal(): void;
    visitProjectableNodesInternal(nodeIndex: number, ngContentIndex: number, cb: any, ctx: any): void;
    handleEvent_18(eventName: string, $event: any): boolean;
}
