/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import9 from 'ionic-angular/components/nav/nav';
import * as import10 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
export declare class Wrapper_MyApp {
    _eventHandler: Function;
    context: import0.MyApp;
    _changed: boolean;
    constructor(p0: any);
    ngOnDetach(view: import1.AppView<any>, componentView: import1.AppView<any>, el: any): void;
    ngOnDestroy(): void;
    ngDoCheck(view: import1.AppView<any>, el: any, throwOnChange: boolean): boolean;
    checkHost(view: import1.AppView<any>, componentView: import1.AppView<any>, el: any, throwOnChange: boolean): void;
    handleEvent(eventName: string, $event: any): boolean;
    subscribe(view: import1.AppView<any>, _eventHandler: any): void;
}
export declare const MyAppNgFactory: import7.ComponentFactory<import0.MyApp>;
export declare class View_MyApp0 extends import1.AppView<import0.MyApp> {
    _text_0: any;
    _el_1: any;
    compView_1: import1.AppView<import9.Nav>;
    _Nav_1_3: import10.Wrapper_Nav;
    _text_2: any;
    constructor(viewUtils: import3.ViewUtils, parentView: import1.AppView<any>, parentIndex: number, parentElement: any);
    createInternal(rootSelector: string): import7.ComponentRef<any>;
    injectorGetInternal(token: any, requestNodeIndex: number, notFoundResult: any): any;
    detectChangesInternal(throwOnChange: boolean): void;
    destroyInternal(): void;
}
